services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    networks:
      - app-network
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB=mongodb+srv://jeebalajee7:dlJnE2gIZRNdEw5V@cluster0.lvzj4.mongodb.net/finance-manager?retryWrites=true&w=majority
      - JWT_SECRET=HKUfr$&*Htrl57g6*kM9hRmPlSvT&@4pN%50ktHRG
      - SALT=10
      - PORT=5000
      - NODE_ENV=production
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "wget", "http://localhost:5000/api/login", "-q", "-O", "-"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge