name: Finance Manager CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install

    - name: Install Backend Dependencies
      run: |
        cd backend
        npm install

    - name: Verify Frontend Dev Server
      run: |
        cd frontend
        npm run dev & 
        sleep 10
        kill $!

    - name: Verify Backend Dev Server
      run: |
        cd backend
        npm run dev &
        sleep 10
        kill $!

    - name: Build Frontend
      run: |
        cd frontend
        npm run build